### PR TITLE
Add brass articulations and double whole noteheads

### PR DESCRIPTION
**Pull request by rettinghaus**

### CODE REVIEW

**Comment by rettinghaus** [comment]
image

**Comment by rettinghaus** [comment]
Added newly designed glyphs for double whole notes.
image

**Comment by rettinghaus** [comment]
Also metadata file has been updated.

**Comment by rettinghaus** [comment]
Latest commit adds missing glyphs for the complete rest and bar rest ranges.
rests_and_repeat_bar_ranges

**Comment by rettinghaus** [comment]
Previously bar lines and repetition dots were added (following the default values from Verovio).
bar_lines

**Comment by lpugin** [comment]
@rettinghaus I think we are missing documentation on how to update the following files:
* FONTLOG.txt
* leipzig_metadata.json

How do you generate them?

**Comment by rettinghaus** [comment]
script added in #11

**Pull request merged**
